basePath: /
host: localhost:8888
info:
  contact: {}
  description: This is a simple blog API with admin panel, markdown support, and pagination.
  title: My Blog API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Login to the admin panel
      parameters:
      - description: Admin Username
        in: formData
        name: username
        required: true
        type: string
      - description: Admin Password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Logged in
          schema:
            type: string
      summary: Login to admin panel
      tags:
      - admin
  /post:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Post a new article from the admin panel
      parameters:
      - description: Article Title
        in: formData
        name: title
        required: true
        type: string
      - description: Article Content
        in: formData
        name: content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: ""
      summary: Post a new article
      tags:
      - admin
  /post/{id}:
    get:
      consumes:
      - application/json
      description: Get a single post by ID
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - text/html
      responses:
        "200":
          description: Post HTML
          schema:
            type: json
        "404":
          description: Not Found
          schema:
            type: string
      summary: Show a single post
      tags:
      - public
swagger: "2.0"
