
all:
ifndef ex
	$(error ex is not set. Usage: make ex=00)
endif
	cd ex$(ex); make

test:
ifndef ex
	$(error ex is not set. Usage: make test ex=00)
endif
	cd ex$(ex); make test

analyze:
ifndef ex
	$(error ex is not set. Usage: make test ex=00)
endif
	cd ex$(ex); make analyze
