version: '3'

services:
  postgres_service:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    restart: on-failure
    ports:
      - 5432:5432
    
